"""
Predictor — loads serialized ML artifacts once at startup and exposes
a thread-safe predict() method used by the FastAPI route handlers.
"""
import os
import numpy as np
import joblib
from pathlib import Path

# Absolute path to the pickled model artifacts
ML_OUTPUTS = Path(__file__).resolve().parents[1] / "ml" / "outputs"

FEATURE_ORDER = ["Age", "SystolicBP", "DiastolicBP", "BS", "BodyTemp", "HeartRate"]

DISCLAIMER = (
    "⚠️ This prediction is generated by an ML model for RESEARCH / EDUCATIONAL "
    "purposes only. It must be reviewed and validated by a qualified clinician "
    "before any clinical decision is made."
)


class MaternalRiskPredictor:
    """Singleton wrapper around the trained Random Forest model."""

    _model = None
    _scaler = None
    _le = None
    _loaded: bool = False

    @classmethod
    def load(cls) -> None:
        """Load model artifacts from disk. Called once at app startup."""
        model_path  = ML_OUTPUTS / "random_forest_model.pkl"
        scaler_path = ML_OUTPUTS / "scaler.pkl"
        le_path     = ML_OUTPUTS / "label_encoder.pkl"

        for p in [model_path, scaler_path, le_path]:
            if not p.exists():
                raise FileNotFoundError(
                    f"[Predictor] Artifact not found: {p}\n"
                    "Run backend/ml/maternal_risk_pipeline.py first to generate model files."
                )

        cls._model  = joblib.load(model_path)
        cls._scaler = joblib.load(scaler_path)
        cls._le     = joblib.load(le_path)
        cls._loaded = True
        print(f"[Predictor] Maternal risk model loaded from {ML_OUTPUTS}")

    @classmethod
    def is_loaded(cls) -> bool:
        return cls._loaded

    @classmethod
    def predict(
        cls,
        age: float,
        systolic_bp: float,
        diastolic_bp: float,
        blood_sugar: float,
        body_temp: float,
        heart_rate: float,
    ) -> dict:
        """
        Run inference for a single patient.

        Returns:
            dict with risk_level, probabilities, confidence, disclaimer
        """
        if not cls._loaded:
            raise RuntimeError("Model not loaded. Call MaternalRiskPredictor.load() first.")

        # Build feature vector in the exact order the model was trained on
        X_raw = np.array([[age, systolic_bp, diastolic_bp, blood_sugar, body_temp, heart_rate]])
        X_scaled = cls._scaler.transform(X_raw)

        pred_idx   = cls._model.predict(X_scaled)[0]
        pred_proba = cls._model.predict_proba(X_scaled)[0]

        risk_label   = cls._le.inverse_transform([pred_idx])[0]
        probabilities = dict(zip(cls._le.classes_, pred_proba.round(4).tolist()))
        confidence    = float(pred_proba.max())

        return {
            "risk_level":    risk_label,
            "probabilities": probabilities,
            "confidence":    round(confidence, 4),
            "disclaimer":    DISCLAIMER,
            "model_version": "random_forest_v1",
        }


# ── Fetal Risk heuristic (placeholder until a CTG model is trained) ──────────

def predict_fetal_risk_heuristic(
    abnormal_stv: float,
    pct_abnormal_ltv: float,
    accelerations: float,
    decelerations_late: float,
    uterine_contractions: float,
) -> dict:
    """
    Rule-based fetal risk classifier based on standard CTG interpretation
    guidelines. Replace with a trained model when CTG training data is available.
    """
    score = (
        (2 if abnormal_stv > 70 else 1 if abnormal_stv > 50 else 0)
        + (2 if pct_abnormal_ltv > 50 else 1 if pct_abnormal_ltv > 30 else 0)
        + (1 if accelerations < 0.001 else 0)
        + (2 if decelerations_late > 0.01 else 0)
        + (1 if uterine_contractions > 5 else 0)
    )

    if score >= 4:
        status, confidence = "Pathological", 0.89
    elif score >= 2:
        status, confidence = "Suspect", 0.76
    else:
        status, confidence = "Normal", 0.98

    return {
        "status":     status,
        "confidence": confidence,
        "disclaimer": DISCLAIMER,
    }
